const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const localTime=d=>new Date(d).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});
const SUPABASE_URL='https://hbewkflvocskgiypgjft.supabase.co';
const SUPABASE_KEY='sb_publishable_6oQ0xG2TskM37fjf3mv_7A_9WX2dG-X';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const USERS={icha:{email:'khususrandom404@gmail.com',display:'Icha'},cenos:{email:'aldisyahsihombing@gmail.com',display:'Cenos'}};
let currentUser=null,products=[],transactions=[],transactionItems=[],stockLogs=[],suppliers=[],purchases=[],finances=[],customers=[],cart=[],syncing=false;
let settings={id:null,storeName:'Kasir Toko',address:'',footer:'Terima kasih telah berbelanja'};
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};
function fail(e,msg='Terjadi kesalahan.'){console.error(e);alert(e?.message||msg)}
function userFromEmail(email){let a=Object.entries(USERS).find(([,u])=>u.email.toLowerCase()===String(email||'').toLowerCase());return a?{username:a[0],display:a[1].display,email:a[1].email}:null}
async function login(e){e.preventDefault();$('loginError').textContent='';let username=$('username').value.trim().toLowerCase(),profile=USERS[username];if(!profile){$('loginError').textContent='Nama kasir tidak ditemukan.';return}let {data,error}=await db.auth.signInWithPassword({email:profile.email,password:$('password').value});if(error){$('loginError').textContent='Nama kasir atau kata sandi salah.';return}currentUser={username,display:profile.display,email:data.user.email};await showApp()}
async function logout(){await db.auth.signOut();location.reload()}
$('loginForm').onsubmit=login;$('logout').onclick=logout;
async function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');$('activeUser').textContent=currentUser.display;await loadData()}
async function loadData(silent=false){if(syncing)return;syncing=true;try{let [p,t,ti,sm,su,pu,fi,cu,se]=await Promise.all([db.from('products').select('*').order('name'),db.from('transactions').select('*').order('created_at',{ascending:false}),db.from('transaction_items').select('*'),db.from('stock_movements').select('*').order('created_at',{ascending:false}),db.from('suppliers').select('*').order('name'),db.from('purchases').select('*').order('created_at',{ascending:false}),db.from('finance_logs').select('*').order('created_at',{ascending:false}),db.from('customers').select('*').order('name'),db.from('store_settings').select('*').limit(1)]);let bad=[p,t,ti,sm,su,pu,fi,cu,se].find(x=>x.error);if(bad)throw bad.error;products=(p.data||[]).map(x=>({id:x.id,code:x.code,name:x.name,buy:+x.buy_price,sell:+x.sell_price,stock:+x.stock,minStock:+(x.min_stock||5)}));transactionItems=ti.data||[];transactions=(t.data||[]).map(x=>({id:x.id,code:x.transaction_code,cashier:x.cashier||'-',method:x.payment_method||'Cash',total:+x.total,profit:+x.profit,pay:+x.paid,change:+x.change_amount,date:localDate(new Date(x.created_at)),time:localTime(x.created_at),items:transactionItems.filter(i=>i.transaction_id===x.id).map(i=>({id:i.product_id,name:i.product_name,qty:+i.qty,buy:+i.buy_price,sell:+i.sell_price}))}));stockLogs=(sm.data||[]).map(x=>({id:x.id,productId:x.product_id,type:x.movement_type,qty:+x.qty,note:x.note||'',cashier:x.cashier||'-',date:localDate(new Date(x.created_at)),time:localTime(x.created_at)}));suppliers=su.data||[];purchases=(pu.data||[]).map(x=>({id:x.id,supplierId:x.supplier_id,productId:x.product_id,qty:+x.qty,cost:+x.unit_cost,total:+x.total,note:x.note||'',cashier:x.cashier||'-',date:localDate(new Date(x.created_at)),time:localTime(x.created_at)}));finances=(fi.data||[]).map(x=>({id:x.id,type:x.type,category:x.category,amount:+x.amount,note:x.note||'',cashier:x.cashier||'-',date:localDate(new Date(x.created_at)),time:localTime(x.created_at)}));customers=cu.data||[];if(se.data?.[0])settings={id:se.data[0].id,storeName:se.data[0].store_name||'Kasir Toko',address:se.data[0].address||'',footer:se.data[0].receipt_footer||'Terima kasih telah berbelanja'};renderAll()}catch(e){if(!silent)fail(e,'Gagal mengambil data online.')}finally{syncing=false}}
function renderProducts(){let q=($('productSearch').value||'').toLowerCase(),list=products.filter(p=>p.name.toLowerCase().includes(q)||p.code.toLowerCase().includes(q));$('productTable').innerHTML=list.length?list.map(p=>`<tr><td>${p.code}</td><td><b>${p.name}</b></td><td>${money(p.buy)}</td><td>${money(p.sell)}</td><td>${p.stock}</td><td><button class="small" onclick="editProduct(${p.id})">Edit</button> <button class="danger small" onclick="deleteProduct(${p.id})">Hapus</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">Belum ada produk</td></tr>`;let cq=($('cashierSearch').value||'').toLowerCase(),cp=products.filter(p=>p.name.toLowerCase().includes(cq)||p.code.toLowerCase().includes(cq));$('cashierProducts').innerHTML=cp.length?cp.map(p=>`<div class="product-card"><b>${p.name}</b><small>${p.code} • Stok ${p.stock}</small><strong>${money(p.sell)}</strong><button onclick="addCart(${p.id})" ${p.stock<=0?'disabled':''}>Tambah</button></div>`).join(''):'<div class="empty">Produk tidak ditemukan</div>';$('stockProduct').innerHTML=products.length?products.map(p=>`<option value="${p.id}">${p.code} - ${p.name} (stok ${p.stock})</option>`).join(''):'<option value="">Belum ada produk</option>';$('purchaseProduct').innerHTML=products.length?products.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''):'<option value="">Belum ada produk</option>'}
$('productSearch').oninput=renderProducts;$('cashierSearch').oninput=renderProducts;
$('addProductBtn').onclick=()=>openModal('Produk Baru',`<label>Kode / Barcode</label><input id="mCode"><label>Nama Produk</label><input id="mName"><label>Harga Modal</label><input id="mBuy" type="number"><label>Harga Jual</label><input id="mSell" type="number"><label>Stok Awal</label><input id="mStock" type="number"><button onclick="saveProduct()">Simpan Produk</button>`);
async function saveProduct(id=null){let code=$('mCode').value.trim(),name=$('mName').value.trim(),buy=+$('mBuy').value,sell=+$('mSell').value,stock=+$('mStock').value;if(!code||!name||sell<=0||stock<0)return alert('Lengkapi data produk.');let r=id?await db.from('products').update({code,name,buy_price:buy,sell_price:sell,stock}).eq('id',id):await db.from('products').insert({code,name,buy_price:buy,sell_price:sell,stock});if(r.error)return fail(r.error);closeModal();await loadData()}
function editProduct(id){let p=products.find(x=>x.id===id);if(!p)return;openModal('Edit Produk',`<label>Kode / Barcode</label><input id="mCode" value="${p.code}"><label>Nama Produk</label><input id="mName" value="${p.name}"><label>Harga Modal</label><input id="mBuy" type="number" value="${p.buy}"><label>Harga Jual</label><input id="mSell" type="number" value="${p.sell}"><label>Stok</label><input id="mStock" type="number" value="${p.stock}"><button onclick="saveProduct(${p.id})">Simpan Perubahan</button>`)}
async function deleteProduct(id){if(!confirm('Hapus produk ini?'))return;let r=await db.from('products').delete().eq('id',id);if(r.error)return fail(r.error,'Produk mungkin sudah dipakai pada transaksi.');await loadData()}
function addCart(id){let p=products.find(x=>x.id===id),c=cart.find(x=>x.id===id);if(!p||p.stock<=0)return;if(c){if(c.qty>=p.stock)return alert('Stok tidak cukup');c.qty++}else cart.push({id:p.id,name:p.name,buy:p.buy,sell:p.sell,qty:1});renderCart()}
function cartQty(id,d){let c=cart.find(x=>x.id===id),p=products.find(x=>x.id===id);if(!c||!p)return;if(d>0&&c.qty>=p.stock)return alert('Stok tidak cukup');c.qty+=d;if(c.qty<=0)cart=cart.filter(x=>x.id!==id);renderCart()}
function cartTotal(){return cart.reduce((s,c)=>s+c.sell*c.qty,0)}
function renderCart(){$('cart').innerHTML=cart.length?cart.map(c=>`<div class="cartrow"><div><b>${c.name}</b><small>${money(c.sell)} × ${c.qty}</small></div><div class="qty"><button onclick="cartQty(${c.id},-1)">−</button> <b>${c.qty}</b> <button onclick="cartQty(${c.id},1)">+</button></div><b>${money(c.sell*c.qty)}</b></div>`).join(''):'<div class="empty">Keranjang kosong</div>';$('cartTotal').textContent=money(cartTotal());calcChange()}
function calcChange(){let total=cartTotal(),pay=+$('payAmount').value;$('change').textContent=money(Math.max(0,pay-total))}
$('payAmount').oninput=calcChange;$('clearCart').onclick=()=>{cart=[];renderCart()};
$('checkout').onclick=async()=>{if(!cart.length)return alert('Keranjang kosong');await loadData(true);for(let c of cart){let p=products.find(x=>x.id===c.id);if(!p||p.stock<c.qty)return alert(`Stok ${c.name} tidak cukup.`)}let total=cartTotal(),method=$('paymentMethod').value,pay=+$('payAmount').value;if(method==='Cash'&&pay<total)return alert('Uang bayar kurang');let profit=cart.reduce((s,c)=>s+(c.sell-c.buy)*c.qty,0),code='TRX-'+Date.now().toString().slice(-8);let {data:trx,error}=await db.from('transactions').insert({transaction_code:code,cashier:currentUser.display,payment_method:method,total,profit,paid:method==='Cash'?pay:total,change_amount:method==='Cash'?pay-total:0}).select().single();if(error)return fail(error);let items=cart.map(c=>({transaction_id:trx.id,product_id:c.id,product_name:c.name,qty:c.qty,buy_price:c.buy,sell_price:c.sell,subtotal:c.sell*c.qty}));({error}=await db.from('transaction_items').insert(items));if(error)return fail(error);for(let c of cart){let p=products.find(x=>x.id===c.id),r=await db.from('products').update({stock:p.stock-c.qty}).eq('id',c.id);if(r.error)return fail(r.error);await db.from('stock_movements').insert({product_id:c.id,movement_type:'sale',qty:-c.qty,note:code,cashier:currentUser.display})}cart=[];$('payAmount').value='';await loadData();alert('Transaksi berhasil dan tersimpan online.')};
$('addStockBtn').onclick=async()=>{let id=+$('stockProduct').value,qty=+$('stockQty').value,note=$('stockNote').value.trim(),p=products.find(x=>x.id===id);if(!p||qty<=0)return alert('Isi stok dengan benar');let r=await db.from('products').update({stock:p.stock+qty}).eq('id',id);if(r.error)return fail(r.error);r=await db.from('stock_movements').insert({product_id:id,movement_type:'stock_in',qty,note,cashier:currentUser.display});if(r.error)return fail(r.error);$('stockQty').value='';$('stockNote').value='';await loadData()};
function renderStock(){$('stockHistory').innerHTML=stockLogs.length?stockLogs.slice(0,30).map(x=>{let p=products.find(y=>y.id===x.productId);return `<div class="listrow"><div><b>${p?.name||'Produk'}</b><small>${x.date} ${x.time} • ${x.note||'-'} • ${x.cashier}</small></div><b class="${x.qty>=0?'in':'out'}">${x.qty>=0?'+':''}${x.qty}</b></div>`}).join(''):'<div class="empty">Belum ada riwayat stok</div>'}
$('addSupplierBtn').onclick=()=>openModal('Supplier Baru',`<label>Nama Supplier</label><input id="mSupplierName"><label>Telepon</label><input id="mSupplierPhone"><label>Alamat</label><input id="mSupplierAddress"><button onclick="saveSupplier()">Simpan Supplier</button>`);
async function saveSupplier(){let name=$('mSupplierName').value.trim();if(!name)return alert('Nama supplier wajib diisi');let r=await db.from('suppliers').insert({name,phone:$('mSupplierPhone').value,address:$('mSupplierAddress').value});if(r.error)return fail(r.error);closeModal();await loadData()}
async function deleteSupplier(id){if(!confirm('Hapus supplier?'))return;let r=await db.from('suppliers').delete().eq('id',id);if(r.error)return fail(r.error);await loadData()}
function renderSuppliers(){$('supplierList').innerHTML=suppliers.length?suppliers.map(s=>`<div class="listrow"><div><b>${s.name}</b><small>${s.phone||'-'} • ${s.address||'-'}</small></div><button class="danger small" onclick="deleteSupplier(${s.id})">Hapus</button></div>`).join(''):'<div class="empty">Belum ada supplier</div>';$('purchaseSupplier').innerHTML=suppliers.length?suppliers.map(s=>`<option value="${s.id}">${s.name}</option>`).join(''):'<option value="">Tambahkan supplier terlebih dahulu</option>'}
$('savePurchase').onclick=async()=>{let sid=+$('purchaseSupplier').value,pid=+$('purchaseProduct').value,qty=+$('purchaseQty').value,cost=+$('purchaseUnitCost').value,p=products.find(x=>x.id===pid),s=suppliers.find(x=>x.id===sid),note=$('purchaseNote').value.trim();if(!s)return alert('Silakan tambahkan atau pilih supplier terlebih dahulu.');if(!p)return alert('Silakan pilih produk.');if(qty<=0||cost<0)return alert('Lengkapi jumlah dan harga modal pembelian.');let total=qty*cost,r=await db.from('purchases').insert({supplier_id:sid,product_id:pid,qty,unit_cost:cost,total,note,cashier:currentUser.display});if(r.error)return fail(r.error);r=await db.from('products').update({stock:p.stock+qty,buy_price:cost}).eq('id',pid);if(r.error)return fail(r.error);await db.from('stock_movements').insert({product_id:pid,movement_type:'purchase',qty,note:`${s.name}${note?' • '+note:''}`,cashier:currentUser.display});r=await db.from('finance_logs').insert({type:'out',category:'Belanja Stok',amount:total,note:`Pembelian ${p.name} x${qty} dari ${s.name}`,cashier:currentUser.display});if(r.error)return fail(r.error);$('purchaseQty').value='';$('purchaseUnitCost').value='';$('purchaseNote').value='';await loadData();alert(`Pembelian berhasil. Stok ${p.name} bertambah ${qty}.`)};
function renderPurchases(){$('purchaseHistory').innerHTML=purchases.length?purchases.slice(0,40).map(x=>{let s=suppliers.find(y=>y.id===x.supplierId),p=products.find(y=>y.id===x.productId);return `<div class="listrow"><div><b>${p?.name||'Produk'} × ${x.qty}</b><small>${x.date} ${x.time} • ${s?.name||'Supplier'} • ${x.note||'-'}</small></div><b>${money(x.total)}</b></div>`}).join(''):'<div class="empty">Belum ada pembelian</div>'}
$('saveFinance').onclick=async()=>{let amount=+$('financeAmount').value;if(amount<=0)return alert('Nominal belum benar');let r=await db.from('finance_logs').insert({type:$('financeType').value,category:$('financeCategory').value,amount,note:$('financeNote').value.trim(),cashier:currentUser.display});if(r.error)return fail(r.error);$('financeAmount').value='';$('financeNote').value='';await loadData()};
async function deleteFinance(id){if(!confirm('Hapus catatan keuangan?'))return;let r=await db.from('finance_logs').delete().eq('id',id);if(r.error)return fail(r.error);await loadData()}
function financeTotals(date=localDate()){let sales=transactions.filter(t=>t.date===date).reduce((s,t)=>s+t.total,0),arr=finances.filter(f=>f.date===date),manualIn=arr.filter(f=>f.type==='in').reduce((s,f)=>s+f.amount,0),out=arr.filter(f=>f.type==='out').reduce((s,f)=>s+f.amount,0);return{incoming:sales+manualIn,out,balance:sales+manualIn-out}}
function renderFinance(){let f=financeTotals();$('fIn').textContent=money(f.incoming);$('fOut').textContent=money(f.out);$('fBalance').textContent=money(f.balance);$('financeHistory').innerHTML=finances.length?finances.slice(0,50).map(x=>`<div class="listrow"><div><b>${x.category}</b><small>${x.date} ${x.time} • ${x.note||'-'} • ${x.cashier}</small></div><b class="${x.type}">${x.type==='in'?'+':'-'} ${money(x.amount)}</b><button class="danger small" onclick="deleteFinance(${x.id})">Hapus</button></div>`).join(''):'<div class="empty">Belum ada catatan keuangan</div>'}
$('addCustomerBtn').onclick=()=>openModal('Pelanggan Baru',`<label>Nama</label><input id="mCustomerName"><label>Telepon</label><input id="mCustomerPhone"><label>Catatan</label><input id="mCustomerNote"><button onclick="saveCustomer()">Simpan Pelanggan</button>`);
async function saveCustomer(){let name=$('mCustomerName').value.trim();if(!name)return alert('Nama pelanggan wajib diisi');let r=await db.from('customers').insert({name,phone:$('mCustomerPhone').value,note:$('mCustomerNote').value});if(r.error)return fail(r.error);closeModal();await loadData()}
async function deleteCustomer(id){if(!confirm('Hapus pelanggan?'))return;let r=await db.from('customers').delete().eq('id',id);if(r.error)return fail(r.error);await loadData()}
function renderCustomers(){$('customerList').innerHTML=customers.length?customers.map(c=>`<div class="listrow"><div><b>${c.name}</b><small>${c.phone||'-'} • ${c.note||'-'}</small></div><button class="danger small" onclick="deleteCustomer(${c.id})">Hapus</button></div>`).join(''):'<div class="empty">Belum ada pelanggan</div>'}
function renderDashboard(){let d=localDate(),arr=transactions.filter(t=>t.date===d),rev=arr.reduce((s,t)=>s+t.total,0),profit=arr.reduce((s,t)=>s+t.profit,0),f=financeTotals(d);$('dRevenue').textContent=money(rev);$('dProfit').textContent=money(profit);$('dExpense').textContent=money(f.out);$('dBalance').textContent=money(f.balance);$('dTransactions').textContent=arr.length;$('dStock').textContent=products.reduce((s,p)=>s+p.stock,0);$('recentTx').innerHTML=arr.length?arr.slice(0,7).map(t=>`<div class="listrow"><div><b>${t.code}</b><small>${t.time} • ${t.cashier} • ${t.method}</small></div><b>${money(t.total)}</b></div>`).join(''):'<div class="empty">Belum ada transaksi hari ini</div>';let low=products.filter(p=>p.stock<=p.minStock);$('lowStock').innerHTML=low.length?low.map(p=>`<div class="listrow"><div><b>${p.name}</b><small>${p.code}</small></div><b class="out">${p.stock}</b></div>`).join(''):'<div class="empty">Stok aman</div>'}
function renderReport(){let date=$('reportDate').value||localDate(),arr=transactions.filter(t=>t.date===date),rev=arr.reduce((s,t)=>s+t.total,0),profit=arr.reduce((s,t)=>s+t.profit,0),f=financeTotals(date);$('reportSummary').innerHTML=`<article><span>Omzet</span><b>${money(rev)}</b></article><article><span>Keuntungan</span><b>${money(profit)}</b></article><article><span>Pengeluaran</span><b>${money(f.out)}</b></article><article><span>Saldo Kas</span><b>${money(f.balance)}</b></article>`;$('reportTransactions').innerHTML=arr.length?`<div class="tablewrap"><table><thead><tr><th>Kode</th><th>Jam</th><th>Kasir</th><th>Metode</th><th>Total</th><th>Keuntungan</th></tr></thead><tbody>${arr.map(t=>`<tr><td>${t.code}</td><td>${t.time}</td><td>${t.cashier}</td><td>${t.method}</td><td>${money(t.total)}</td><td>${money(t.profit)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Tidak ada transaksi</div>'}
$('reportDate').value=localDate();$('reportDate').onchange=renderReport;
function renderSettings(){$('storeName').value=settings.storeName;$('storeAddress').value=settings.address;$('receiptFooter').value=settings.footer}
$('saveSettings').onclick=async()=>{let payload={store_name:$('storeName').value.trim()||'Kasir Toko',address:$('storeAddress').value.trim(),receipt_footer:$('receiptFooter').value.trim(),updated_at:new Date().toISOString()},r=settings.id?await db.from('store_settings').update(payload).eq('id',settings.id):await db.from('store_settings').insert(payload);if(r.error)return fail(r.error);await loadData();alert('Pengaturan disimpan online.')};
function renderAll(){$('today').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});renderProducts();renderCart();renderStock();renderSuppliers();renderPurchases();renderFinance();renderCustomers();renderDashboard();renderReport();renderSettings()}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=async()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(b.dataset.page).classList.add('active');$('pageTitle').textContent=b.textContent.replace(/^[^A-Za-zÀ-ÿ]+/,'').trim();await loadData(true)});
(async()=>{let {data:{session}}=await db.auth.getSession();if(session?.user){currentUser=userFromEmail(session.user.email);if(currentUser)await showApp();else await db.auth.signOut()}})();
setInterval(()=>{if(currentUser&&!document.hidden)loadData(true)},5000);